#!/usr/bin/env bash
## Prints help dialog for all scripts in the directory of the help file
cd "$(dirname "$0")"

printf "\033[1;34mCommands:\033[1;0m\n"
for file in ./*; do
    if [[ -x "$file" ]]; then
        description="$(awk '/\#\#\ .*/{ print $0 }' ${file})"
        separator="$(printf "%-$((20 - ${#file}))s" ' ')"
        printf "  \033[1;35m${file/\.\//}\033[1;0m${separator}${description/\#\#/}\n"
    fi
done
